.circleci/config.yml
Add circle CI configuration to build the app/chart and publish to the catalog
=> Add correct CI configuration

README.md, helm/logging-app-chart/.helmignore, helm/logging-app-chart/Chart.yaml, helm/logging-app-chart/templates/fluentbit/configmap.yaml, helm/logging-app-chart/templates/fluentbit/daemonset.yaml, helm/logging-app-chart/templates/fluentbit/network-policy.yaml, helm/logging-app-chart/templates/fluentbit/psp.yaml, helm/logging-app-chart/templates/fluentbit/rbac.yaml, helm/logging-app-chart/templates/fluentbit/service.yaml, helm/logging-app-chart/templates/fluentbit/serviceaccount.yaml, helm/logging-app-chart/templates/fluentd/configmap.yaml, helm/logging-app-chart/templates/fluentd/deployment.yaml, helm/logging-app-chart/templates/fluentd/network-policy.yaml, helm/logging-app-chart/templates/fluentd/psp.yaml, helm/logging-app-chart/templates/fluentd/rbac.yaml, helm/logging-app-chart/templates/fluentd/service.yaml, helm/logging-app-chart/templates/fluentd/serviceaccount.yaml, helm/logging-app-chart/values.yaml
Add fluentbit plus fluentd to let customers send logs (ssh,k8s audit and containers to S3)
=> Add fluentd and fluentbit chart

CHANGELOG.md, helm/fluent-logshipping-app-chart/Chart.yaml, helm/fluent-logshipping-app-chart/templates/fluentd/configmap.yaml, helm/fluent-logshipping-app-chart/values.yaml
Otherwise non-root users cannot open the files :)
=> Allow set up the owner of the object in S3 calls

CHANGELOG.md, README.md, helm/fluent-logshipping-app-chart/templates/fluentbit/service.yaml, helm/fluent-logshipping-app-chart/templates/fluentd/service.yaml, helm/fluent-logshipping-app-chart/values.yaml
Toward https://github.com/giantswarm/giantswarm/issues/7259
It will be the best practice for the changes to have monitoring support in our managed app.
=> Support monitoring of apps by adding annotations

helm/fluent-logshipping-app/Configuration.md
The description is already in the main README and header was wrong :)
=> Clean up configuration docs

helm/fluent-logshipping-app/Azure.md, helm/fluent-logshipping-app/Configuration.md
Just because it takes so long to find the shared key
=> Add docs for finding the workspace id and shared key on azure portal

CHANGELOG.md, README.md, helm/fluent-logshipping-app/Configuration.md, helm/fluent-logshipping-app/templates/fluentd/configmap.yaml, helm/fluent-logshipping-app/templates/fluentd/deployment.yaml, helm/fluent-logshipping-app/templates/fluentd/secret.yaml, helm/fluent-logshipping-app/values.yaml
WIP but if you want to check before I test the setup :)
=> Add Elasticsearch access

CHANGELOG.md, helm/fluent-logshipping-app/Chart.yaml, helm/fluent-logshipping-app/templates/fluentbit/configmap.yaml, helm/fluent-logshipping-app/templates/fluentd/configmap.yaml
Customer is testing this setup. He will get back to me after a few hours but so far it seem to work
=> Improving performances for elasticsearch and rename labels

helm/fluent-logshipping-app/Chart.yaml
This updates the app icon to use our static web assets server.
=> Update app icon

CHANGELOG.md, helm/fluent-logshipping-app/values.schema.json
This adds a values.schema.json generated from the current values.yaml using helm schema-gen. Related: giantswarm/roadmap#152
=> Add values.json.schema

CHANGELOG.md, helm/fluent-logshipping-app/templates/fluentd/deployment.yaml, helm/fluent-logshipping-app/values.yaml
=> FIX: Use correct mountpath for fluentd config

helm/fluent-logshipping-app/templates/fluentd/deployment.yaml, helm/fluent-logshipping-app/values.yaml
It has the plugins baked in to the image
=> Use GS Docker image for fluentd

helm/fluent-logshipping-app/templates/configmap.yaml, helm/fluent-logshipping-app/values.yaml
- Create option to add additional outputs and filters
- Give ability for user to disable certain outputs
This is useful for when the user only wants certain logs (i.e they don't
need container logs or only want k8s audit)
=> Give some flexibilty around filters and outputs

CHANGELOG.md, helm/fluent-logshipping-app/templates/configmap.yaml
This helps prevent hitting API limits
=> [Cloudwatch Output] Break up the stream names

helm/fluent-logshipping-app/values.yaml
Towards: giantswarm/giantswarm#19055
=> update image to fluent-bit:1.7.1-systemd247

CHANGELOG.md
Towards: https://github.com/giantswarm/giantswarm/issues/19055
=> update changelog for systemd change

helm/fluent-logshipping-app/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/19663
=> Add team annotation to chart

CHANGELOG.md, helm/fluent-logshipping-app/templates/service.yaml
issue: https://github.com/giantswarm/roadmap/issues/719
Fixing Prometheus metrics path in the service annotation.
=> Fix scrape target path

CHANGELOG.md, helm/fluent-logshipping-app/templates/configmap.yaml, helm/fluent-logshipping-app/templates/daemonset.yaml, helm/fluent-logshipping-app/templates/secret.yaml, helm/fluent-logshipping-app/values.yaml
Adds s3 endpoint and access keys support for CEPH backed s3 endpoints
=> Add s3 endpoint and access key suport

CHANGELOG.md, helm/fluent-logshipping-app/Chart.yaml, helm/fluent-logshipping-app/templates/configmap.yaml
=> add-auditd-execve-logs

CHANGELOG.md, helm/fluent-logshipping-app/templates/_resource.tpl, helm/fluent-logshipping-app/templates/vpa.yaml, helm/fluent-logshipping-app/values.yaml
Closes https://github.com/giantswarm/giantswarm/issues/23049
=> Add VPA support

helm/fluent-logshipping-app/templates/configmap.yaml
Towards https://github.com/giantswarm/giantswarm/issues/24993
=> Add host name to auditd logs

CHANGELOG.md, helm/fluent-logshipping-app/templates/daemonset.yaml, helm/fluent-logshipping-app/templates/psp.yaml, helm/fluent-logshipping-app/templates/rbac.yaml
Towards https://github.com/giantswarm/roadmap/issues/2389
=> Deprecate master node labels

CHANGELOG.md, helm/fluent-logshipping-app/templates/kyverno-policy-exception.yaml, helm/fluent-logshipping-app/values.schema.json, helm/fluent-logshipping-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/27340
=> Add kyverno policy exceptions

CHANGELOG.md, helm/fluent-logshipping-app/Configuration.md, helm/fluent-logshipping-app/templates/service.yaml, helm/fluent-logshipping-app/templates/servicemonitor.yaml, helm/fluent-logshipping-app/values.schema.json, helm/fluent-logshipping-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/27145 tested on Gauss
=> Add Service Monitor

CHANGELOG.md, helm/fluent-logshipping-app/Chart.yaml, helm/fluent-logshipping-app/templates/configmap.yaml, helm/fluent-logshipping-app/templates/vpa.yaml, helm/fluent-logshipping-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/24992
=> Add ausearch support to work with auditd

CHANGELOG.md, helm/fluent-logshipping-app/templates/psp.yaml, helm/fluent-logshipping-app/templates/rbac.yaml, helm/fluent-logshipping-app/values.schema.json, helm/fluent-logshipping-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28337
This PR adds a new switch for PSP disablement to transition to PSS
=> Disable psp switch

CHANGELOG.md, helm/fluent-logshipping-app/templates/configmap.yaml
Towards https://github.com/giantswarm/vodafone-iot-portal/issues/48
See this for context https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support
=> Fix multi-line-parsing

CHANGELOG.md, helm/fluent-logshipping-app/templates/configmap.yaml, helm/fluent-logshipping-app/templates/daemonset.yaml, helm/fluent-logshipping-app/templates/persistencevolumeclaim.yaml, helm/fluent-logshipping-app/values-cloudwatch.yaml, helm/fluent-logshipping-app/values.schema.json, helm/fluent-logshipping-app/values.yaml
This PR adds supports for PVC storage to keep the tracked files on fluent-bit restarts.
=> Support PVC

CHANGELOG.md, helm/fluent-logshipping-app/templates/configmap.yaml, helm/fluent-logshipping-app/values.yaml
As requested by a customer, let's allow them to disable the export of execve logs
=> Add possibility to disable the execve audit logs

CHANGELOG.md, helm/fluent-logshipping-app/values.yaml
This PR bumps fluent-bit image to a version with the auditd lib
=> Fix missing auditd libs
